// <auto-generated />
using System;
using Ems.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ems.Data.Migrations
{
    [DbContext(typeof(EmployeesContext))]
    [Migration("20200122113333_Employee_Id_Autogenerate")]
    partial class Employee_Id_Autogenerate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ems.Data.Models.Employee", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned");

                    b.Property<uint>("GradeId")
                        .HasColumnName("grade_id")
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<decimal>("PersonalCostMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("personal_cost_multiplier")
                        .HasColumnType("decimal(5,3)")
                        .HasDefaultValueSql("1.000");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnName("position_id")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("GradeId")
                        .HasName("grade_id");

                    b.HasIndex("PositionId")
                        .HasName("position_id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("Ems.Data.Models.Grade", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned");

                    b.Property<decimal?>("CostMultiplier")
                        .HasColumnName("cost_multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("grade");
                });

            modelBuilder.Entity("Ems.Data.Models.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("CostRate")
                        .HasColumnName("cost_rate")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.ToTable("position");
                });

            modelBuilder.Entity("Ems.Data.Models.Employee", b =>
                {
                    b.HasOne("Ems.Data.Models.Grade", "Grade")
                        .WithMany("Employee")
                        .HasForeignKey("GradeId")
                        .HasConstraintName("employee_ibfk_1")
                        .IsRequired();

                    b.HasOne("Ems.Data.Models.Position", "Position")
                        .WithMany("Employee")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("employee_ibfk_2")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
