// <auto-generated />
using System;
using Ems.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ems.Data.Migrations
{
    [DbContext(typeof(EmployeesContext))]
    partial class EmployeesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ems.Data.Models.Employee", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<DateTimeOffset>("EmploymentDate")
                        .HasColumnType("datetime(6)")
                        .IsUnicode(false);

                    b.Property<uint>("GradeId")
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<decimal>("PersonalCostMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,3)")
                        .HasDefaultValueSql("1.000");

                    b.Property<uint>("PositionId")
                        .HasColumnType("int(10) unsigned")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Ems.Data.Models.Grade", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<decimal?>("CostMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("Ems.Data.Models.Position", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned");

                    b.Property<int>("CostRate")
                        .HasColumnType("int(11)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Ems.Data.Models.Employee", b =>
                {
                    b.HasOne("Ems.Data.Models.Grade", "Grade")
                        .WithMany("Employee")
                        .HasForeignKey("GradeId")
                        .HasConstraintName("employee_ibfk_1")
                        .IsRequired();

                    b.HasOne("Ems.Data.Models.Position", "Position")
                        .WithMany("Employee")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("employee_ibfk_2")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
